// Registro das telas que podem ser liberadas individualmente por usuário.
// Para adicionar uma nova tela controlável, inclua um item aqui, proteja a
// rota com o middleware requireTela('<chave>') e associe o item do menu.
// A sincronização com a tabela "telas" acontece no atualizardb().
const TELAS = [
  {
    chave: "dashboard",
    nome: "Dashboard",
    rota: "/dash",
    icone: "bi-speedometer2",
    grupo: "Principal",
    ordem: 1,
  },
  {
    chave: "pedidos",
    nome: "Pedidos",
    rota: "/pedidos",
    icone: "bi-receipt",
    grupo: "Principal",
    ordem: 2,
  },
  {
    chave: "clientes",
    nome: "Clientes",
    rota: "/clientes",
    icone: "bi-people",
    grupo: "Principal",
    ordem: 3,
  },
  {
    chave: "produtos",
    nome: "Produtos",
    rota: "/painel",
    icone: "bi-box-seam",
    grupo: "Catálogo",
    ordem: 4,
  },
  {
    chave: "promocoes",
    nome: "Promoções",
    rota: "/promocoes",
    icone: "bi-tag",
    grupo: "Catálogo",
    ordem: 5,
  },
  {
    chave: "grupos",
    nome: "Grupos (peças)",
    rota: "/part",
    icone: "bi-diagram-3",
    grupo: "Catálogo",
    ordem: 6,
  },
  {
    chave: "devolucoes",
    nome: "Devoluções",
    rota: "/devolucoes",
    icone: "bi-arrow-counterclockwise",
    grupo: "Operações",
    ordem: 7,
  },
  {
    chave: "estoque",
    nome: "Estoque",
    rota: "/estoque",
    icone: "bi-boxes",
    grupo: "Operações",
    ordem: 8,
  },
  {
    chave: "estoque-grupos",
    nome: "Estoque Grupos",
    rota: "/estoque-grupos",
    icone: "bi-collection",
    grupo: "Operações",
    ordem: 9,
  },
  {
    chave: "relatorios",
    nome: "Relatórios",
    rota: "/relatorios",
    icone: "bi-bar-chart",
    grupo: "Ferramentas",
    ordem: 10,
  },
  {
    chave: "backups",
    nome: "Backups",
    rota: "/backup",
    icone: "bi-database",
    grupo: "Ferramentas",
    ordem: 11,
  },
  {
    chave: "vitrines",
    nome: "Vitrines",
    rota: "/vitrines",
    icone: "bi-shop-window",
    grupo: "Catálogo",
    ordem: 12,
  },
  {
    chave: "usuarios",
    nome: "Usuários",
    rota: "/users",
    icone: "bi-person-badge",
    grupo: "Ferramentas",
    ordem: 13,
  },
  {
    chave: "configuracoes",
    nome: "Configurações",
    rota: "/configuracoes",
    icone: "bi-gear",
    grupo: "Ferramentas",
    ordem: 14,
  },
];

module.exports = TELAS;
